drop table public.beneficiaries_tab ;

create
	table
		public.beneficiaries_tab(
			beneficiaries_id integer not null generated by default as identity(
				start with 1
			),
			wycc_id varchar(2000) null,
			name varchar(2000) null,
			first_name varchar(2000) null,
			line decimal(
				65535,
				32767
			) null,
			structure_name varchar(2000) null,
			family_covered varchar(2000) null,
			children varchar(2000) null,
			nationality varchar(2000) null,
			country varchar(2000) null,
			positioncrew varchar(2000) null,
			period_insurance varchar(2000) null,
			start_movement timestamp null,
			prevmvt date null,
			endcomp bigint null,
			end_movement timestamp null,
			nextmvt date null,
			nextcomp bigint null,
			monthly_salary decimal(
				65535,
				32767
			) null,
			salary_currency varchar(2000) null,
			drestej integer null,
			erestej integer null,
			to_invoice float null,
			jour decimal(
				10,
				1
			) null,
			mois float null,
			company1 varchar(500),
			formule_name1 varchar(500),
			total_amount_insured1 float,
			company2 varchar(500),
			formule_name2 varchar(500),
			total_amount_insured2 float,
			company3 varchar(500),
			formule_name3 varchar(500),
			total_amount_insured3 float,
			company4 varchar(500),
			formule_name4 varchar(500),
			total_amount_insured4 float,
			company5 varchar(500),
			formule_name5 varchar(500),
			total_amount_insured5 float,
			company6 varchar(500),
			formule_name6 varchar(500),
			total_amount_insured6 float,
			company7 varchar(500),
			formule_name7 varchar(500),
			total_amount_insured7 float,
			company8 varchar(500),
			formule_name8 varchar(500),
			total_amount_insured8 float
		);
